config/routes.rb
Rails.application.routes.draw do


  resources :shopping_lists, only: [:index]
  


  get 'items/create'

  root to: 'pages#home'




  devise_for :users, path: 'users', controllers: { 
    sessions: "users/sessions" 
  }
  devise_for :drivers, path: 'drivers', controllers: { 
    sessions: "drivers/sessions" 
  }

  resources :shopping_lists, only: [:index, :new, :create, :show, :edit, :update, :picks, :destroy] do
    resources :items, only: [:new, :create, :show]
  end

  get "/shopping_lists/:user_id/view_all", to: "shopping_lists#view_all", as: "view_all"
  get "/orders/:id/create_order", to: "orders#create_order", as: "create_order"
  get "/orders/:driver_id/picks", to: "orders#picks", as: "picks"
  post "/orders/:id/deliver", to: "orders#mark_as_delivered", as: "order_delivered"



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/_footer.html.erb
<!-- <footer class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
  </div>
  <div class="footer-copyright" style="color: rgb(0,0,0);">
    © 2020 ShopHelper
  </div>
</footer>
 -->
    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
      </div>
      <div class="footer-copyright" style="color: rgb(240,240,240);">
        Thanks for making the community a better place <i class="fas fa-heart"></i>
      </div>
      <div style="color: rgb(240,240,240);">
        © 2020 ShopHelper
      </div>
    </div>

app/views/pages/_form_html.erb
<!-- app/views/articles/_form.html.erb -->
<%= simple_form_for(user) do |f| %>
  <!-- [...] -->
  <%= f.input :photo, as: :file %>
  <!-- [...] -->
<% end %>

app/views/pages/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <% home_link = root_path %>
  <% home_link = new_shopping_list_path if user_signed_in? && !current_user.shopping_list %>
  <% home_link = shopping_list_path(current_user.shopping_list) if user_signed_in? && current_user.shopping_list %>
  <% home_link = shopping_lists_path if driver_signed_in? %>

  <%= link_to home_link, class: "navbar-brand" do %>
    <%= image_tag("New14.png") %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto" style="color: #2780F5">
      <% if user_signed_in? %>
        <li class="nav-item d-flex">
          <%= link_to "Create Shopping List", new_shopping_list_path(current_user), class: "nav-link" %>
          <%= link_to "My Shopping Lists", view_all_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <div class="avatar" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path current_user.photo.key, height: 400, width: 400, crop: :fill %>') "></div>
          <% else %>
          <div class="avatar" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://kitt.lewagon.com/placeholder/users/arthur-littm')"></div>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% elsif driver_signed_in? %>
        <li class="nav-item">
          <%= link_to "My Picks", picks_path(current_driver), class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_driver.photo.attached? %>
            <div class="avatar" id="navbarDropdown"data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path current_driver.photo.key, height:400, width:400, crop: :fill %>') "></div>
          <% else %>
          <div class="avatar" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://kitt.lewagon.com/placeholder/users/sarahlafer')"></div>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit Profile", edit_driver_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_driver_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item px-2">
            <%= link_to "Become A Driver", new_driver_registration_path, class: "border-driver" %>
          </li>
        <li class="nav-item dropdown px-3">
          <div class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="far fa-user" style="font-weight: lighter;"></i> Login</div>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "User Login", new_user_session_path, class: "dropdown-item" %>
            <%= link_to "Driver Login", new_driver_session_path, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/pages/home.html.erb
<body class="homepage">
  <div class="banner">
    <%= image_tag('landing-photo.jpg', class: "landing-photo") %>
    <div class="value-proposition">
      <h2>Stay home.</h2>
      <h2>Someone will shop for you.</h2>
      <br>
      <%= link_to "Post your shopping list", new_shopping_list_path, class: "btn btn-blue" %>
    </div>
  </div>
  <div class="container" style="height: 100vh">
    <div class="caption" style="font-size: 1.3rem">
      <p style="font-weight: lighter;">ShopHelper gives <span style="font-weight: bold">people in need</span> the opportunity to <span style="font-weight: bold">connect with volunteers</span> through our simple and effective platform.
      After registration, users can immediately <span style="font-weight: bold">post their desired shopping list</span>. The shopping lists are picked up by our drivers,
      who shop on their behalf and <span style="font-weight: bold">deliver the goods directly to their home</span>.</p>
    </div>
    <div class="cards">
      <div class="card-category" style="background-image: linear-gradient(to right, rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(<%= asset_path 'user.jpg' %>)">
        <div class="content d-block">
          <div style="font-size: 24px">Create your shopping list</div>
          <%= link_to "Want to publish a list? Sign up here", new_user_registration_path, class: "card-link" %>
        </div>
      </div>

      <div class="card-category" style="background-image: linear-gradient(to right, rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(<%= asset_path 'driver.jpg' %>)">
        <div class="content d-block">
          <div style="font-size: 24px">Let our drivers shop for you</div>
          <%= link_to "Want to deliver? Sign up here", new_driver_registration_path, class: "card-link" %>
        </div>
      </div>

      <div class="card-category" style="background-image: linear-gradient(to right, rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(<%= asset_path 'deliver.jpg' %>)">
        <div class="content d-block">
          <div style="font-size: 24px">We deliver your order</div>
        </div>
      </div>
    </div>
  </div>
</body>