config/routes.rb
Rails.application.routes.draw do


  resources :shopping_lists, only: [:index]
  


  get 'items/create'

  root to: 'pages#home'




  devise_for :users, path: 'users', controllers: { 
    sessions: "users/sessions" 
  }
  devise_for :drivers, path: 'drivers', controllers: { 
    sessions: "drivers/sessions" 
  }

  resources :shopping_lists, only: [:index, :new, :create, :show, :edit, :update, :picks, :destroy] do
    resources :items, only: [:new, :create, :show]
  end

  get "/shopping_lists/:user_id/view_all", to: "shopping_lists#view_all", as: "view_all"
  get "/orders/:id/create_order", to: "orders#create_order", as: "create_order"
  get "/orders/:driver_id/picks", to: "orders#picks", as: "picks"
  post "/orders/:id/deliver", to: "orders#mark_as_delivered", as: "order_delivered"



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :user
  has_one :order, dependent: :destroy
  has_one :driver, through: :order
  has_many :items, dependent: :destroy
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  before_action :find_shoppingList, only: [:update, :show, :destroy]
  before_action do |controller|
    if ['new', 'create', 'update'].include? controller.action_name
      authenticate_user!
    elsif controller.action_name == 'show'
      if !user_signed_in? && !driver_signed_in?
        authenticate_user!
      end
    elsif controller.action_name == 'index'
      authenticate_driver!
    end
  end

   def index
    @users = User.geocoded
    # @shopping_lists = ShoppingList.all
   @shopping_lists = []

   @users.each do |user|
     if user.shopping_list != nil && user.shopping_list.status != false
       @shopping_lists << user.shopping_list
     end
   end
    @markers = @shopping_lists.map do |shopping_list|
      {
        lat: shopping_list.user.latitude,
        lng: shopping_list.user.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { user: shopping_list.user }),
        picture: helpers.asset_url("cart-color.jpg")
      }
    end
  end


  def new
    @shopping_list = ShoppingList.new
    @items = Item.new
    create
  end

  def create
    @shopping_list = ShoppingList.new(status: true, user: current_user)

    if @shopping_list.save!
      redirect_to new_shopping_list_item_path(@shopping_list)
    else
      render :new
    end
  end


  def update
    @shopping_list.update(form_params)
    redirect_to shopping_list_path(@shopping_list)
  end


  #This method returns ONLY ONE ShoppingList
  def show
  end

  def destroy
    @shopping_list.destroy
    redirect_to  view_all_path(current_user)
  end

  def view_all
    @shopping_lists = ShoppingList.where(user_id: current_user.id)
  end



private

  def find_shoppingList
    @shopping_list = ShoppingList.find(params[:id])
    @items = Item.where("shopping_list_id = ?", params[:id])
  end


  def form_params
    params.require(:shopping_list).permit(:notes)
  end

end

app/views/shopping_lists/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/shopping_lists/_info_window.html.erb
<h5><%= user.first_name  %></h5>
<h5><%= user.location  %></h5>

app/views/shopping_lists/create.html.erb
<h1>ShoppingLists#create</h1>
<p>Find me in app/views/shopping_lists/create.html.erb</p>

app/views/shopping_lists/destroy.html.erb
<h1>ShoppingLists#destroy</h1>
<p>Find me in app/views/shopping_lists/destroy.html.erb</p>

app/views/shopping_lists/edit.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product</th>
      <th scope="col">Quantity</th>
    </tr>
  </thead>
  <tbody>
    <% if @items %>
        <% n = 0 %>
        <% @items.each do |i| %>
        <tr>
          <% n += 1 %>
          <th scope="row"><%= n %></th>
          <td><%= i.product_name %></td>
          <td><%= i.quantity %></td>
        </tr>
        <% end %>
      <% end %>
  </tbody>
</table>

<div class="m-3">
<%= simple_form_for @shoppingList do |s| %>
  <%= s.simple_fields_for :items do |i| %>
    <%= i.input :product_name %>
    <%= i.input :quantity %>
  <% end %>
  <%= s.input :notes %>
  <%= s.submit "Add item to shopping list"  %>
<% end %>
</div>

<%= link_to "Done with shopping", shopping_list_path, class: "btn btn-ghost" %>

app/views/shopping_lists/index.html.erb
<div class= "mx-3">
  <div class = "row">
    <div class="col-12 col-md-6 col-lg-6 mt-5">
      <h4 style="margin-left: 18px;">Available shopping lists:</h4>
      <% @shopping_lists.each do |shoppinglist|  %>
          <div class="notification mt-2 ml-3">
          <%= image_tag('cart-color.jpg', class: "avatar-large") %>
            <div class="notification-content">

              <p>Order Created by:<strong>  <%= shoppinglist.user.first_name %></strong> </p>
              <p><small>number of items in the shopping list: <%=  shoppinglist.items.count %></small></p>
              <p>
                <% if params[:lat] && params[:lng] %>
                <i class="fas fa-location-arrow"></i>
                <%=  shoppinglist.user.distance_to([params[:lat], params[:lng]]).round%> Km
              <% end %>
              </p>
            </div>

            <div class="notification-actions">
              <%= link_to  shopping_list_path(shoppinglist) do %>
                 <i class="far fa-eye"></i>
              <% end %>
            </div>
          </div>
      <%end%>
    </div>

    <div class="col-12 col-md-6 col-lg-6">
      <div
      id="map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="pk.eyJ1Ijoicm9kb2xmb3AiLCJhIjoiY2s4MDl6cG9sMGNnaDNkcGcyaml4YXJ1MCJ9.fTw_XIDzAzHw5clxchO04A"
      ></div>
    </div>
  </div>
</div>

app/views/shopping_lists/new.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class=".col-sm-12 col-md-4">
    </div>
    <div class=".col-sm-12 col-md-4">
        <div class="card-empty">
          <%= simple_form_for(@shopping_list) do |f| %>
            <%= f.submit "+", class: "card-btn-empty"%>
          <% end %>
        </div>
    </div>
    <div class=".col-sm-12 col-md-4">
    </div>
  </div>
</div>

app/views/shopping_lists/show.html.erb
<div class="container">
  <div class="row justify-content-center ">

    <div class=".col-sm-12 col-md-2">
    </div>
<!-- 1) IF DRIVER: -->

    <% if current_driver %>
      <div class=".col-sm-12 col-md-4">
          <div class="notification-list mt-5">
            <div class="notification-layer mt-5 mb-4">
              <strong>Grocery List:</strong>
            </div>
            <% if @items %>
              <% @items.each do |i| %>
              <div class="notification-layer mt-3 ml-3">
                <p>
                  <%= i.quantity %> x
                  <%= i.product_name %>
                </p>
              </div>
              <% end %>
            <% end %>
        </div>
    </div>

    <div class=".col-sm-12 col-md-4">
      <div class="notification-show mt-5">

                <%if @shopping_list.user.photo.attached? %>
                  <%= cl_image_tag @shopping_list.user.photo.key, class:"avatar avatar-show-position" %>
                <%else%>
                  <%= image_tag('avatar.png', class: "avatar avatar-show-position") %>
                <%end%>
        <div class="notification-layer1 mt-5 ml-4">
              <p><strong>
                    <%= @shopping_list.user.first_name %> <%= @shopping_list.user.last_name %>
              </strong></p>
        </div>
        <div class="notification-layer2 ml-4">
            <p>
              <strong>Note from <%= @shopping_list.user.first_name %>:</strong><br>
              <%if @shopping_list.notes%>
                <small class="ml-2">  <%= @shopping_list.notes %> </small>
              <%else%>
                <small class="ml-2"> No notes...! Thanks for your help! </small>
              <%end%>
            </p>
            <p><br>
             <strong> Delivery point:</strong> <br>
             <small class="ml-2"> <%= @shopping_list.user.location %></small>
            </p>
        </div>

<!-- 1.1) IF RESQUEST IS NOT PICKED: -->
          <% if @shopping_list.status %>
            <div class="pl-3">
              <%= link_to "Help this user", create_order_path(@shopping_list), class: "btn-gradient btn-show-dr-position2" %>
              <%= link_to "Go back", shopping_lists_path, class: "btn-gradient btn-show-dr-position" %>
             </div>
<!-- 1.2) IF RESQUEST IS NOT DELIVERED: -->
          <% else %>
              <% if @shopping_list.order.status %>
                <div class="pl-3">
                  <%= link_to "Mark as deliver", order_delivered_path(@shopping_list.order), method: :post, remote:true, class: "btn-gradient btn-show-dr-position" %>
                  <%= link_to "Go back", shopping_lists_path, class: "btn-gradient btn-show-dr-position3" %>
                </div>
<!-- 1.3) IF RESQUEST IS DELIVERED: -->
              <%else%>
                <div class="pl-3">
                  <%= link_to "You've delivered this order. Back!", picks_path(current_driver), class: "btn-gradient btn-show-dr-position" %>
                </div>
              <%end%>
          <% end %>
      </div>
<!-- 2) IF USER: -->

    <% elsif current_user %>
    <div class=".col-sm-12 col-md-4">
         <div class="notification-list mt-5">
            <div class="delivery-layer bl">
              <%if @shopping_list.status %>
                <div>
                  <img src="https://pedservices.py.gov.in/Content/images/loading.gif" class="caffe">
                </div>
                <strong>Pending...</strong>
              <% else %>
                <strong>On its way!</strong>
              <%end%>
            </div>
            <div class="notification-layer mt-4 mb-4">
              <strong>My Grocery List:</strong>
            </div>
        <% if @items %>
          <% @items.each do |i| %>
            <div class="notification-layer mt-1 ml-2">
                <p>
                  <%= i.quantity %> x
                  <%= i.product_name %>
                </p>
            </div>
          <% end %>
        <% end %>
        </div>
    </div>

    <div class=".col-sm-12 col-md-4">
       <div class="notification-show mt-5">
          <div class="notification-layer mt-4">

            <!-- 2.1) IF NOT DELIVERED: -->
            <%if @shopping_list.status %>
            <p><strong> Your shopping list has been posted!</strong></p> <br>
            <p><strong class="bl">
                  Wait until someone helps you ... <br>
                  <small>
                    Looks like people is quite busy at this moment, please be patient, a driver will accept your grocery list very soon.
                  </small>
            </strong></p>
            <!-- 2.2) IF  DELIVERED: -->
            <% else %>
            <p><strong class="bl">
                 <%= @shopping_list.driver.first_name %> is helping you... <br>
                <small>
                 The driver could contact you during the day, please keep your phone close.
                </small>
            </strong></p>
            <% end %>
          </div>
          <div class="notification-layer mt-3">
            <%if !@shopping_list.notes %>
                <%= simple_form_for(@shopping_list, remote: true) do |shop| %>
                  <%= shop.input_field :notes, class: "form_txtarea", placeholder: 'Write your note here....'  %>
                  <%= shop.submit "Add" , class: "btn-gradient " ,style: "margin-left: 13px"  %>
                <% end %>
            <% end %>
              <%if @shopping_list.notes %>
              <div class="note-pos">
                <p> <strong>Your Note: </strong> <br>
                     <small> <%= @shopping_list.notes %> </small>
                </p>
                </div>
              <%end%>
              <div class="mt-1">
                <a href="#" class="mt-5"> <%= link_to "Go to your lists!", view_all_path(current_user), class: "btn-gradient mt-5 btn-list-position", style: "margin: 13px"  %> </a>
              </div>
          </div>

        </div>
      <%end%>
    </div>

    <div class=".col-sm-12 col-md-2">
    </div>
  </div>
</div>

app/views/shopping_lists/update.html.erb
<h1>ShoppingLists#update</h1>
<p>Find me in app/views/shopping_lists/update.html.erb</p>

app/views/shopping_lists/view_all.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class=".col-sm-12 col-md-3">
    </div>
    <div class=".col-sm-12 col-md-6">
      <h4>My shopping lists:</h4>
      <%if !@shopping_lists.empty? %>
        <% @shopping_lists.each do |list| %>
          <div class="notification">
          <%= image_tag('Cart3.png', class: "cart-large") %>
            <div class="notification-content">
              <p><small>Order Created at: <%=  list.created_at.time %> </small></p>
              <p>number of items in the shopping list: <%= list.items.count %></strong> </p>
              <p>
                <% if !list.status %>
                <i class="far fa-check-circle"></i>
              <% end %>
              </p>
            </div>

            <div class="notification-actions">
              <%= link_to shopping_list_path(list) do %>
                 <i class="far fa-eye"></i>
              <% end %>
              <%= link_to shopping_list_path(list), method: :delete, remote: true do %>
                 <i class="far fa-trash-alt"></i>
              <% end %>
            </div>
          </div>
          <% end %>
          <div class="notification">
              <div class="notification-content mt-5 mb-5">
                <p> <small>Want to make a new shopping list?</small></p>
              </div>
              <div class="pl-3">
                  <%= link_to "Create one!", new_shopping_list_path, class: "btn-gradient " %>
              </div>
          </div>
      <%else %>
        <div class="notification">
          <div class="notification-content mt-5 mb-5">
            <p> <small>No shopping list is added yet...</small></p>
          </div>
          <div class="pl-3">
              <%= link_to "Create a shopping list!", new_shopping_list_path, class: "btn-gradient " %>
          </div>
        </div>
      <%end%>
    </div>
    <div class=".col-sm-12 col-md-3">
    </div>
  </div>
</div>